# Site settings
title: hcraT
email: tarcisio.fedrizzi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hcrat.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "hcrat.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  hcraT

# Build settings
markdown: kramdown
